idf_component_register(
    SRCS 
        "main.cpp"
        "hal/WiFiManager.cpp"
        "hal/UdpSender.cpp"
        "hal/UartDriver.cpp"
        "utils/Utils.cpp"
    INCLUDE_DIRS 
        "hal"
        "utils"
        "../../../common"
    REQUIRES
        esp_wifi
        esp_event
        esp_netif
        esp_timer
        esp_driver_uart
        esp_driver_gpio
        nvs_flash
        lwip
)